### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by csgruenebe** [dtrunk90/thymeleaf-jawr-extension#2]
Could you provide some examples of how the syntax can be exactly used inside a thymeleaf template.
That would be great :)

**Comment by csgruenebe** [comment]
I found this in some forum. Perhaps you could provide this in a readme:

JS
```
<script jawr:script="/javascript/jquery-1.6.1.js" src="/javascript/jquery-1.6.1.js"></script>
```
CSS
```
<link jawr:style="/css/styles-all.css" />
```
To use it in a Spring MVC environment, just modify the template engine bean definition like this: 
```
<bean id="templateEngine" class="org.thymeleaf.spring3.SpringTemplateEngine">
	<property name="templateResolver" ref="templateResolver" />
	<property name="dialects">
		<set>
			<bean class="org.thymeleaf.spring3.dialect.SpringStandardDialect" />
			<bean class="com.google.code.thymeleaf.jawr.JawrDialect" />
		</set>
	</property>
</bean>
```

**Comment by dtrunk90** [comment]
I'll provide a README.md asap

**Comment by mknezic** [comment]
If you need help, I can give you some examples as I'm using it in a big project, which caused this whole code by FingolfinTEK to be created.

**Comment by csgruenebe** [comment]
I already got it working, thank you.

**Comment by dtrunk90** [comment]
The one from FingolfinTEK/mknezic (https://github.com/mknezic/thymeleaf-jawr-extension) is based on spring 3 (https://github.com/mknezic/thymeleaf-jawr-extension/blob/master/src/main/java/com/googlecode/thymeleaf/jawr/JawrDialect.java#L37) and not available through maven central repositories. As well as it is not possible to use expressions as attribute values. That's why I forked it.

**Comment by mknezic** [comment]
Yep, no problem with forking it. Glad someone continued work on it.
